### ISSUE TITLE
TLS Error on exec

### ISSUE THREAD

**Issue by DefunctExodus** [containerd/cri#712] opened 2018-04-02 12:19 UTC
Good Morning,

I have recently upgraded my cluster to 1.10 and the latest release of this plugin,  I noticed that `exec`, `attach` and `portforward` are now encrypted.

I am sure I am missing something but with these now being encrypted how exactly do i get around the TLS error?

**Comment by mikebrow** [comment] 2018-04-02 13:28
Not aware of a TLS error. Can you elaborate.

**Comment by DefunctExodus** [comment] 2018-04-02 13:51
Sure sorry, did that on my phone this morning

I am seeing this following error `TLS handshake error from XX.XX.XX.XX:55048: remote error: tls: bad certificate`

Initially when i ran into this error on Friday i figured it was something with my setup and the upgrade to 1.10, i suppose it could still be however this only happens when this plugin. I eventually ended up switching back to using docker to see if i was able to `exec` into a test container and it worked correctly.

Using this plugin i see no errors during startup or  looking at the logs of a container. It only happens when i am trying to `exec` in.

**Comment by mikebrow** [comment] 2018-04-02 13:55
exec in using crictl?  

If crictl need to get you to move up to the latest version. If you are running from developer environment just need to make install.deps..

**Comment by DefunctExodus** [comment] 2018-04-02 13:56
Sorry my bad i am talking about getting into the container through Kubernetes

**Comment by mikebrow** [comment] 2018-04-02 13:57
kube 1.10? with containerd 1.10?

**Comment by DefunctExodus** [comment] 2018-04-02 13:58
yeah

**Comment by mikebrow** [comment] 2018-04-02 13:58
ok will have to check it out... thx

**Comment by Random-Liu** [comment] 2018-04-02 15:57
@mikebrow We may want to make the encryption optional. In GKE, we don't validate certificate, but I guess in other setup, people may do that.

Let's make the encryption opt-in.

**Comment by mikebrow** [comment] 2018-04-02 17:47
done.. let's push #714 when it passes ..

**Comment by Random-Liu** [comment] 2018-04-02 18:26
@DefunctExodus I can't reproduce this in my cluster, `kubectl exec` works in my cluster.

How did you setup your cluster?

**Comment by DefunctExodus** [comment] 2018-04-02 18:55
@Random-Liu 

Yep it is, I actually took this node out of the cluster and rebuilt it using TLS Bootstrapping, The node successfully joins the cluster and works as you would except.

The only thing that is not working right now is `kubectl exec` 

The rest of my nodes are still running 1.9.2 and CRI beta 1 and it works correctly, and like i said switching to using docker as the run-time engine does not produce this error.

**Comment by Random-Liu** [comment] 2018-04-02 19:54
@DefunctExodus 

Why docker works? - Dockershim is part of kubelet today, and its streaming server is part of kubelet server. If your kubelet server certificate is valid, the dockershim streaming server will be valid as well.

Why cri beta 1 works? - We don't use TLS in that version.

Why the newest `cri` doesn't work? - We use unsigned certificate in containerd streaming server to make the connection encrypted, but we don't have a valid CA. To solve this problem, a greater change need to be designed and implemented in Container Runtime Interface, which we couldn't get to soon.

@DefunctExodus  Do you only need the streaming server certificate to be signed? Or do you also need the CA to be valid?

If it is the former, we can switch to a self-signed certificate? If it is the latter, I don't think we can resolve it in short term. We can get https://github.com/containerd/cri/pull/714 in, so that you can disable the TLS.

**Comment by DefunctExodus** [comment] 2018-04-02 20:18
@Random-Liu 

Thanks for the explanation that makes complete sense.

I think having the streaming cert signed by the CA would be good enough,  But having a way to disable it  would also be ideal and give more flexibility to it.

The only reason i brought it up is because when migrating from `beta` to `rc` i had expected to maintain the same functionality. I noticed the `tls` commit and assume it was something along those lines so i figured why not post an issue.

Thanks for looking at this so quickly.

**Comment by Random-Liu** [comment] 2018-04-03 00:03
@DefunctExodus https://github.com/containerd/cri/pull/714 added a config option to enable streaming server TLS `enable_tls_streaming`, it is false by default.

That fix will be included in the coming `v1.0.0-rc.1` release. :) This should be enough for your case.

A more comprehensive discussion about how to handle TLS in CRI container runtime is in https://github.com/kubernetes/kubernetes/issues/36666.

**Closed by Random-Liu** 2018-04-03 00:03 UTC
