### ISSUE TITLE
Plugin-only cri-containerd

### ISSUE THREAD

**Issue by dnephin** [containerd/cri#594] opened 2018-02-04 18:45 UTC
This issue is in reference to https://github.com/containerd/containerd/pull/1615#issuecomment-362764604, also https://github.com/containerd/containerd/pull/2096#issuecomment-362759770 and https://github.com/containerd/cri-containerd/pull/523#issuecomment-362927189

> Another requirement we have is for testing. After we make cri-containerd a containerd plugin, we can't test it without building with containerd

I'm opening this issue because I couldn't find an existing issue and I want to comment without distracting from the primary topic in containerd/containerd#1615. If there is an existing issue please feel free to close this issue and redirect me there.

cc @Random-Liu

**Comment by dnephin** [comment] 2018-02-04 18:57
Would something like this work:

* `git clone containerd` (separate from vendor)
* `rm -rf containerd/vendor/github.com/containerd/cri-containerd`
* `go build` containerd so that it includes the version of cri-containerd to test

**Comment by Random-Liu** [comment] 2018-02-04 20:16
The problem is that we may update other dependencies in `cri-containerd`. Then we need to figure out:
1) If the dependency is introduced by containerd, we'd better keep it the same with containerd, or else it may not compile.
2) If the dependency is only introduced by cri-containerd, we might need to do something similar with https://github.com/containerd/cri-containerd/issues/594#issuecomment-362930337.

This is what we are doing in https://github.com/containerd/cri-containerd/pull/558.
It is doable, but I don't think it is the best way to do it. :)

**Comment by dnephin** [comment] 2018-02-05 16:49
> If the dependency is introduced by containerd, we'd better keep it the same with containerd, or else it may not compile.

CI will tell us if there are dependencies with backwards incompatible changes. Trying to preemptively sync vendor directories is not necessary. 

> If the dependency is only introduced by cri-containerd, we might need to do something similar with #594 (comment).

Not sure what you mean. Why would you need to do anything special in this case?

**Comment by Random-Liu** [comment] 2018-02-05 18:39
@dnephin See https://github.com/containerd/cri-containerd/pull/523#issuecomment-363177501.

**Comment by Random-Liu** [comment] 2018-04-09 22:42
I think we've resolved this issue by exposing CLI package from containerd. Let's close this one.

**Closed** 2018-04-09 22:43 UTC
