### ISSUE TITLE
cri-containerd cannot pull public image with invalid username/password

### ISSUE THREAD

**Issue by jovizhangwei** [containerd/cri#668] opened 2018-03-15 09:12 UTC
cri-containerd cannot pull public image with username/password.
We expected containerd should pull the public image whatever username/password given or not.

```
# crictl -r /var/run/cri-containerd.sock pull nginx --creds foo:foo
FATA[0002] pulling image failed: rpc error: code = Unknown desc = failed to resolve image "docker.io/library/nginx:latest": failed to fetch oauth token: unexpected status: 401 Unauthorized
```

```
# crictl -r /var/run/cri-containerd.sock pull nginx
Image is update to date for sha256:73acd1f0cfadf6f56d30351ac633056a4fb50d455fd95b229f564ff0a7adecda
```

Compare with docker, docker can pull public image whatever login succeeded or not. 

I tried to report this issue to containerd, but they suggested cri-containerd could do some improvements similar with what docker does.

Please see: https://github.com/containerd/containerd/issues/2211

**Comment by Random-Liu** [comment] 2018-03-15 23:39
@jovizhangwei Just curious, in what case, you need `crictl -r /var/run/cri-containerd.sock pull nginx --creds foo:foo` to work?

**Comment by jovizhangwei** [comment] 2018-03-16 03:16
@Random-Liu take below example:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test1
    image: registry-vpc.cn-hangzhou.aliyuncs.com/jovi/ubuntu #public image
    imagePullPolicy: Always
    command: ["sh", "-c"]
    args: ["set -x; echo $HOSTNAME; sleep 10000"]
  - name: test2
    image: registry-vpc.cn-hangzhou.aliyuncs.com/jovi/nginx:alpine #private image
    imagePullPolicy: Always
    command: ["sh", "-c"]
    args: ["set -x; echo $HOSTNAME; sleep 10000"]
  imagePullSecrets:
  - name: regsecret  #for private image use
  restartPolicy: Never
  automountServiceAccountToken: false
```
Put public image and private image in one pod, with imagePullSecrets for private image. Because public image and private image have some server, so public image will also try to use the imagePullSecrets, then we can found failed to pull public image.

```
Failed to pull image "registry-vpc.cn-hangzhou.aliyuncs.com/jovi/ubuntu": rpc error: code = Unknown desc = failed to resolve image "registry-vpc.cn-hangzhou.aliyuncs.com/jovi/ubuntu:latest": unexpected status code https://registry-vpc.cn-hangzhou.aliyuncs.com/v2/jovi/ubuntu/manifests/latest: 401 Unauthorized
```

If change the container runtime to Docker, then there have no issues.

**Comment by Random-Liu** [comment] 2018-03-16 05:53
@jovizhangwei This makes sense to me. We should fix this @abhi

**Comment by abhi** [comment] 2018-03-16 15:09
I understand the use case here.
The one concern is - if user attaches a wrong secret and because the auth fails , we pull from a public repo without pass, would that mean the user might end up running the un intended image silently? I think that is some concern on how to go about handling.

**Comment by Random-Liu** [comment] 2018-03-16 17:29
> would that mean the user might end up running the un intended image silently?

The image reference is still the same, authentication is not part of image reference, right? Why user might end up running another image?

**Comment by Random-Liu** [comment] 2018-03-23 00:24
I don't think we have time to finish this one for `rc.0` release.

This is a special use case that we should support, but should be fine to support in `rc.1`.

**Comment by Random-Liu** [comment] 2018-04-03 18:32
We plan to cut an early `rc.1` release today to carry several fix and improvement. Move this to `rc.2`.

**Comment by Random-Liu** [comment] 2018-04-05 06:34
@jovizhangwei I tried this with dockershim, and it doesn't work as well:
```
# crictl pull nginx --creds foo:foo
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Error response from daemon: Get https://registry-
1.docker.io/v2/library/nginx/manifests/latest: unauthorized: incorrect username or password
```

**Comment by Random-Liu** [comment] 2018-04-05 06:43
@jovizhangwei Can you tell me how do you generate the random `regsecret`? I could not reproduce it.
```console
$ kubectl create secret docker-registry regsecret --docker-server=docker.io --docker-username=taotaotheripper --docker-password=taotaotheripper --docker-email=taotaotheripper@gmail.com
secret "regsecret" created
$ cat test-image-pull.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test
    image: nginx
    imagePullPolicy: Always
    command: ["sh", "-c"]
    args: ["set -x; echo $HOSTNAME; sleep 10000"]
  imagePullSecrets:
  - name: regsecret
  restartPolicy: Never
$ kubectl create -f test-image-pull.yaml 
pod "test-pod" created
lantaol@workstation:~/workspace/src/k8s.io/kubernetes$ kubectl get pods
NAME                               READY     STATUS    RESTARTS   AGE
test-pod                           1/1       Running   0          6s
```

**Comment by Random-Liu** [comment] 2018-04-05 07:17
One reason might be that I'm using a gcr.io registry mirror, and gcr behaves differently:
```
# cat /etc/containerd/config.toml 
[plugins.linux]
  shim = "/home/containerd/usr/local/bin/containerd-shim"
  runtime = "/home/containerd/usr/local/sbin/runc"

[plugins.cri]
  enable_tls_streaming = true
[plugins.cri.cni]
  bin_dir = "/home/kubernetes/bin"
  conf_dir = "/etc/cni/net.d"
[plugins.cri.registry.mirrors."docker.io"]
  endpoint = ["https://mirror.gcr.io","https://registry-1.docker.io"]
```

Let me try docker registry.

**Comment by Random-Liu** [comment] 2018-04-05 07:33
I've tried several things:
1) Docker without registry mirror:
```console
# ps aux | grep dockerd
root       833  0.1  0.2 1018472 69864 ?       Ssl  Mar28  23:31 /usr/bin/dockerd -H fd://

# crictl -r /run/dockershim.sock pull nginx --creds foo:foo
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/library/nginx/manifests/latest: unauthorized: incorrect username or password
```
2) Docker with gcr registry mirror:
```console
# ps aux | grep dockerd
root      1299  0.6  1.7 462292 65004 ?        Ssl  Mar27  87:52 /usr/bin/dockerd --registry-mirror=https://mirror.
gcr.io --host=fd:// -p /var/run/docker.pid --iptables=false --ip-masq=false --log-level=warn --bip=169.254.123.1/24
 --registry-mirror=https://mirror.gcr.io --log-driver=json-file --log-opt=max-size=10m --log-opt=max-file=5 --live-
restore=false --insecure-registry 10.0.0.0/8

# crictl -r /run/dockershim.sock pull nginx --creds foo:foo
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Error response from daemon: Get https://registry-
1.docker.io/v2/library/nginx/manifests/latest: unauthorized: incorrect username or password
```

3) containerd without registry mirror:
```console
# cat /etc/containerd/config.toml 

# crictl pull nginx --creds foo:foo
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to resolve image "docker.io/library/nginx:latest": failed to fetch oauth token: unexpected status: 401 Unauthorized 
```

4) containerd with gcr registry mirror:
```console
# cat /etc/containerd/config.toml 
[plugins.cri.registry.mirrors."docker.io"]
  endpoint = ["https://mirror.gcr.io"]

# crictl pull nginx --creds foo:foo
Image is update to date for sha256:c5c4e8fa2cf7d87545ed017b60a4b71e047e26c4ebc71eb1709d9e5289f9176f
```

So actually only containerd + gcr registry mirror works for this.

@jovizhangwei Can you clarify your issue? I really can't reproduce it.

And this behavior seems also specific to image registry implementation, which I'm not sure whether we should rely on. /cc our image expert @dmcgowan :)

**Comment by Random-Liu** [comment] 2018-04-06 17:15
@jovizhangwei I'll wait for your response. I can't reproduce this issue. Let's move this out from milestone now.

**Comment by jovizhangwei** [comment] 2018-04-09 04:33
@Random-Liu sorry for this delayed response.

I rechecked my last yaml example, it's my fault to pull "-vpc" public image, that cause failed to authorize the regsecret.

After I changed the image url to non-vpc style, then it can pull public image with wrong creds, so the behavior is same as gcr registry. 

Please ignore my case, and sorry for disrupt.

**Comment by Random-Liu** [comment] 2018-04-09 18:15
@jovizhangwei Thanks! Close this one then.

**Closed by Random-Liu** 2018-04-09 18:15 UTC
Labels: kind/bug
